version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    groups:
      patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#    rebase-strategy: "disabled"