version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    groups:
      patch-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"