codecov:
  branch: master
comment:
  require_changes: true
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2
        base: 1
        branches:
          - master
        informational: false
        only_pulls: false