comment:
  require_changes: true
coverage:
  range: 1..80
  round: down
  status:
    project:
      default:
        target: auto
        threshold: "2"
        base: auto
        branches:
          - master
        informational: false
        only_pulls: false